version: '3'

services:

  agoradb:
    image: mysql:5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agora
    ports: # Dev purpose only
      - "3305:3306"
    networks: 
      - agora

  agorapi:
    depends_on: 
      - agoradb
    build: 
      context: .
      dockerfile: ./dockerfile
    volumes:
      - ./api:/var/workspace/api
    restart: unless-stopped
    ports: # Dev purpose only
      - "3005:3006"
    networks: 
      - agora
  
  agorapp:
    build: 
      context: ./app
      dockerfile: ./dockerfile
    restart: unless-stopped
    ports: 
      - "80:80"
    networks: 
      - agora

networks:
  agora:
    external:
      name: agora