FROM node:latest AS builder

RUN mkdir -p /var/workspace/app
WORKDIR /var/workspace/app
COPY package.json ./
RUN npm install
COPY . .

RUN npm run build

FROM nginx:1.17.9-alpine
RUN apk update && apk upgrade
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder --chown=nginx:nginx /var/workspace/app/build /usr/share/nginx/html